### PR TITLE
Add Box.com support

### PR DESCRIPTION
**Pull request by pedrosousa**
Supports folders with several pages.

### CODE REVIEW

**Comment by fsantini** [comment]
Hi! Thanks a lot for this PR and also for hosting the test file!
Could you please also update the README with the instructions for Box before merging?

Thanks!

**Comment by pedrosousa** [comment]
Sure, I'll update the README.
Let me know if you want me to update the `test.yml` file that runs the tests -- I usually don't update these CI/CD files without asking first.

**Comment by fsantini** [comment]
Great, thanks! I'll wait for your README update.
The yml workflow is already updated, I pushed commit fa5f853 to your PR.

**Comment by pedrosousa** [comment]
OK, I didn't notice! 
One more note: I'm adding Box after all other supported services because it's the less known/used. If I added it in alphabetical order, it would be the first.

**Comment by fsantini** [comment]
Sounds good!

**Comment by fsantini** [comment]
Thank you!

**Pull request merged**
